/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * EmployeeHugeRecords generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`EMPLOYEE_HUGE_RECORDS`", schema = "`SARASWATHI`")
public class EmployeeHugeRecords implements Serializable {

    private Integer empid;
    private String firstname;
    private String lastname;
    private String street;
    private String city;
    private String state;
    private String postcode;
    private String gender;
    private String email;
    private String username;
    private String password;
    private String phone;
    private String nationality;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] picurl;
    private LocalDateTime dateofbirth;

    @Id
    @Column(name = "`EMPID`", nullable = false, scale = 0, precision = 10)
    public Integer getEmpid() {
        return this.empid;
    }

    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    @Column(name = "`FIRSTNAME`", nullable = true, length = 255)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "`LASTNAME`", nullable = true, length = 255)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "`STREET`", nullable = true, length = 255)
    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    @Column(name = "`CITY`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "`STATE`", nullable = true, length = 255)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`POSTCODE`", nullable = true, length = 255)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Column(name = "`GENDER`", nullable = true, length = 10)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`EMAIL`", nullable = true, length = 255)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "`USERNAME`", nullable = true, length = 255)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "`PASSWORD`", nullable = true, length = 255)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "`PHONE`", nullable = true, length = 255)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "`NATIONALITY`", nullable = true, length = 255)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Column(name = "`PICURL`", nullable = true)
    public byte[] getPicurl() {
        return this.picurl;
    }

    public void setPicurl(byte[] picurl) {
        this.picurl = picurl;
    }

    @Column(name = "`DATEOFBIRTH`", nullable = true)
    public LocalDateTime getDateofbirth() {
        return this.dateofbirth;
    }

    public void setDateofbirth(LocalDateTime dateofbirth) {
        this.dateofbirth = dateofbirth;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeeHugeRecords)) return false;
        final EmployeeHugeRecords employeeHugeRecords = (EmployeeHugeRecords) o;
        return Objects.equals(getEmpid(), employeeHugeRecords.getEmpid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpid());
    }
}