/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class PersonFruitsId implements Serializable {

    private Integer fid;
    private Integer pid;

    public Integer getFid() {
        return this.fid;
    }

    public void setFid(Integer fid) {
        this.fid = fid;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PersonFruits)) return false;
        final PersonFruits personFruits = (PersonFruits) o;
        return Objects.equals(getFid(), personFruits.getFid()) &&
                Objects.equals(getPid(), personFruits.getPid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFid(),
                getPid());
    }
}