/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.cascadedb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * CompositeLocking generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`COMPOSITE_LOCKING`")
@IdClass(CompositeLockingId.class)
public class CompositeLocking implements Serializable {

    private Integer version;
    private Integer id;
    private String column3;
    private String column4;

    @Id
    @Column(name = "`VERSION`", nullable = false, scale = 0, precision = 10)
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`COLUMN3`", nullable = true, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    @Column(name = "`COLUMN4`", nullable = true, length = 255)
    public String getColumn4() {
        return this.column4;
    }

    public void setColumn4(String column4) {
        this.column4 = column4;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CompositeLocking)) return false;
        final CompositeLocking compositeLocking = (CompositeLocking) o;
        return Objects.equals(getVersion(), compositeLocking.getVersion()) &&
                Objects.equals(getId(), compositeLocking.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVersion(),
                getId());
    }
}