/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.cascadedb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class CompositeLockingId implements Serializable {

    private Integer version;
    private Integer id;

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CompositeLocking)) return false;
        final CompositeLocking compositeLocking = (CompositeLocking) o;
        return Objects.equals(getVersion(), compositeLocking.getVersion()) &&
                Objects.equals(getId(), compositeLocking.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVersion(),
                getId());
    }
}