/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.datalockingdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SvUpdateVersionRequest implements Serializable {


    @JsonProperty("charcol")
    @NotNull
    private Character charcol;

    @JsonProperty("datecol")
    @NotNull
    private Date datecol;

    public Character getCharcol() {
        return this.charcol;
    }

    public void setCharcol(Character charcol) {
        this.charcol = charcol;
    }

    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvUpdateVersionRequest)) return false;
        final SvUpdateVersionRequest svUpdateVersionRequest = (SvUpdateVersionRequest) o;
        return Objects.equals(getCharcol(), svUpdateVersionRequest.getCharcol()) &&
                Objects.equals(getDatecol(), svUpdateVersionRequest.getDatecol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharcol(),
                getDatecol());
    }
}