/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.datalockingdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * IntVersioning generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`INT_VERSIONING`")
public class IntVersioning implements Serializable {

    private Integer id;
    private String charcol;
    private Date datecol;
    private Integer intversion;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`CHARCOL`", nullable = true, length = 1)
    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    @Column(name = "`DATECOL`", nullable = true)
    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    @Column(name = "`INTVERSION`", nullable = true, scale = 0, precision = 10)
	@Version
    public Integer getIntversion() {
        return this.intversion;
    }

    public void setIntversion(Integer intversion) {
        this.intversion = intversion;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof IntVersioning)) return false;
        final IntVersioning intVersioning = (IntVersioning) o;
        return Objects.equals(getId(), intVersioning.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}