/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.testing16thmarch_10vm.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<SvUserDataAppEnvResponse> executeSV_UserDataAppEnv(Pageable pageable);

    void exportSV_UserDataAppEnv(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}