/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.BlobContentNotFoundException;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.testing16thmarch_10vm.wmstudio.models.query.*;

@Service
public class WMSTUDIOQueryExecutorServiceImpl implements WMSTUDIOQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(WMSTUDIOQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("WMSTUDIOWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "WMSTUDIOTransactionManager", readOnly = true)
    @Override
    public Page<SvEmpHugeDataResponse> executeSV_EmpHugeData(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("SV_EmpHugeData", params, SvEmpHugeDataResponse.class, pageable);
    }

    @Transactional(value = "WMSTUDIOTransactionManager", readOnly = true)
    @Override
    public InputStream getPicurlContentForSV_EmpHugeData(Integer empid) throws EntityNotFoundException {
        Map<String, Object> params = new HashMap<>(0);

        params.put("empid", empid);

        SvEmpHugeDataResponse _result =  queryExecutor.executeNamedQuery("SV_EmpHugeData__identifier", params, SvEmpHugeDataResponse.class);
        if(_result.getPicurl() == null) {
            LOGGER.debug("Blob content not exists for picurl in query SV_EmpHugeData");
            throw new BlobContentNotFoundException(MessageResource.create("com.wavemaker.runtime.blob.content.not.found"), "picurl", "query", "SV_EmpHugeData");
        }
        return new ByteArrayInputStream(_result.getPicurl());
    }

    @Transactional(value = "WMSTUDIOTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportSV_EmpHugeData(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<SvEmpHugeDataResponse> queryInput = new QueryProcedureInput<>("SV_EmpHugeData", params, SvEmpHugeDataResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}