/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.datalockingdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

import com.testing16thmarch_10vm.datalockingdb.models.query.SvUpdateVersionRequest;

@Service
public class DataLockingdbQueryExecutorServiceImpl implements DataLockingdbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DataLockingdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("DataLockingdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "DataLockingdbTransactionManager")
    @Override
    public Integer executeSV_UpdateVersion(SvUpdateVersionRequest svUpdateVersionRequest) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("charcol", svUpdateVersionRequest.getCharcol());
        params.put("datecol", svUpdateVersionRequest.getDatecol());

        return queryExecutor.executeNamedQueryForUpdate("SV_UpdateVersion", params);
    }

}