/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.datalockingdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testing16thmarch_10vm.datalockingdb.models.query.SvUpdateVersionRequest;

public interface DataLockingdbQueryExecutorService {

    Integer executeSV_UpdateVersion(SvUpdateVersionRequest svUpdateVersionRequest);

}