/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thmarch_10vm.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
import org.springframework.web.util.UriComponentsBuilder;

import com.fasterxml.jackson.annotation.JsonView;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.security.xss.XssDisable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testing16thmarch_10vm.wmstudio.service.WMSTUDIOQueryExecutorService;
import com.testing16thmarch_10vm.wmstudio.models.query.*;

@RestController(value = "WMSTUDIO.QueryExecutionController")
@RequestMapping("/WMSTUDIO/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private WMSTUDIOQueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @JsonView(BlobAsUrlView.class)
    @RequestMapping(value = "/queries/SV_EmpHugeData", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "SV_EmpHugeData")
    public Page<SvEmpHugeDataResponse> executeSV_EmpHugeData(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_EmpHugeData");
        Page<SvEmpHugeDataResponse> _result = queryService.executeSV_EmpHugeData(pageable);
        LOGGER.debug("got the result for named query: SV_EmpHugeData, result:{}", _result);
        UriComponentsBuilder _uriBuilder = ServletUriComponentsBuilder.fromRequest(_request);
        _uriBuilder.path("/{empid}/content/{_fieldName_}");
        for(SvEmpHugeDataResponse _content : _result.getContent()) {
            Map<String, Object> _properties = new HashMap(2);
            _properties.put("empid", _content.getEmpid());
            _properties.put("_fieldName_", "picurl");
            if(_content.getPicurl() != null) {
                _content.setPicurl(_uriBuilder.buildAndExpand(_properties).toUriString().getBytes());
            } else {
                _content.setPicurl(null);
            }
        }
        return _result;
    }

    @ApiOperation(value = "Retrives the BLOB content for property picurl in query SV_EmpHugeData")
    @RequestMapping(value = "/queries/SV_EmpHugeData/{empid}/content/picurl", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable getPicurlContentForSV_EmpHugeData(@PathVariable("empid") Integer empid, @RequestParam(value="downloadAsAttachment", defaultValue = "false") boolean downloadAsAttachment, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_EmpHugeData");

        InputStream _result = queryService.getPicurlContentForSV_EmpHugeData(empid);
        return WMMultipartUtils.buildDownloadResponse(_request, _result, downloadAsAttachment);
    }

    @ApiOperation(value = "Returns downloadable file url for query SV_EmpHugeData")
    @RequestMapping(value = "/queries/SV_EmpHugeData/export", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @XssDisable
    public StringWrapper exportSV_EmpHugeData(@RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: SV_EmpHugeData");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "SV_EmpHugeData";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportSV_EmpHugeData( exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

}